FROM apache/airflow:2.8.2

USER root

# Client Docker + outils systeme utiles au DAG
RUN apt-get update && apt-get install -y --no-install-recommends \
    docker.io \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Installer les dependances Python necessaires pour le pipeline
RUN pip install --no-cache-dir \
    openpyxl==3.1.2 \
    mysql-connector-python==8.3.0 \
    python-dotenv==1.0.1 \
    folium==0.16.0 \
    pymongo==4.11.1 \
    motor==3.6.1 \
    pandas==2.2.0
