FROM node:18-alpine

WORKDIR /app

COPY admin/package*.json ./
RUN npm install

COPY admin/ ./

ARG REACT_APP_API_URL=http://localhost:8000
ENV REACT_APP_API_URL=${REACT_APP_API_URL}

RUN npm run build && npm install -g serve

EXPOSE 3001

CMD ["serve", "-s", "build", "-l", "3001"]
